#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#polkit
lxqt-policykit-agent&

#polyba
polybar&

#fonts
font-0 = Iosevka Nerd Font size=12

#primary monitor
#workspaces
bspc monitor DP-0 -d   󰖟    󰚯  󰊖

#second monitor
xrandr --output DP-2 --mode 1920x1080 --rate 144.00 --rotate normal --brightness 0.6 --right-of DP-0
#set wallpaper for primary monitor
xwallpaper --output DP-0 --stretch /home/dd/Pictures/Nier/w54b6ld6hze21.png
#set wallpaper
xwallpaper --output DP-2 --stretch /home/dd/Pictures/Nordic/nier-replicant-artwork-01-3840x2160-1.jpg 
#workspaces
bspc monitor DP-2 -d 󰙯    󰍹    󰣇
#launch polybar

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Spawn apps rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Godot desktop='^4'
bspc rule -a UnrealEditor desktop='^4'
bspc rule -a Steam desktop='^5' state=floating
bspc rule -a Lutris desktop='^5'
bspc rule -a discord desktop='^6'
bspc rule -a thunderbird desktop='^7'
bspc rule -a pavucontrol desktop='^9'
bspc rule -a obsidian desktop='^10'

#Spanw state rules
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

